# Generated by Django 5.0.7 on 2024-09-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_membertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='nid_passport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('gm', 'General Member'), ('admin', 'Administrator'), ('mod', 'Moderator')], default='gm', max_length=5),
        ),
    ]
