# Generated by Django 5.0.7 on 2024-09-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_dob_member_nid_passport_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
