# Generated by Django 5.0.7 on 2024-09-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='nid_passport',
            new_name='nid',
        ),
        migrations.RemoveField(
            model_name='member',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='member',
            name='instagram_link',
        ),
        migrations.AddField(
            model_name='member',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
