# Generated by Django 5.0.7 on 2024-09-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_rename_nid_passport_member_nid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='facebook',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='instagram',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
